---
- Developer:
    - Github Repo:
        - abbr: GH
          href: https://github.com/tilothiele/hzd-relaunch-2026

- Social:
    - Facebook:
        - icon: facebook.png
          href: https://www.facebook.com/Hovawarte.HZD
          description: HZD Facebook Page

- Entertainment:
    - YouTube:
        - abbr: YT
          href: http://www.youtube.com/user/HovawarteHZD