- Website:
    - Joomla:
        href: https://hovwarte.com
        description: Alte Website
        icon: joomla.png

    - Relaunch:
        href: https://relaunch.hovwarte.com
        description: Neue Website
        icon: https://hzd-backend.hovawarte.com/uploads/HZD_logo256_hovawart_zuchtgemeinschaft_deutschland_d1ad6876b0.png

- Monitoring:
    - Umami:
        href: https://umami.hovwarte.com
        description: Umami Analytics
        icon: umami.png

- Werkzeuge:
    - Nextcloud:
        href: https://cloud.hovwarte.com
        description: Cloud Storage
        icon: nextcloud.png

    - Redmine:
        href: http://redmine.hovwarte.com
        description: Redmine Project Management
        icon: redmine.png

    - Media:
        href: http://resourcespace.hovwarte.com
        description: Mediadatenbank
        icon: panorama-variant-outline.png

