export interface CsCsvColumn {
	header: string
	attribute: string
}

export const CS_DOG_COLUMNS: CsCsvColumn[] = [
	{ header: "ID Animal", attribute: 'IdAnimal' },
	{ header: "Given Name", attribute: 'GivenName' },
	{ header: "Name of Breeding Station", attribute: 'NameOfBreedingStation' },
	{ header: "Full Name", attribute: 'FullName' },
	{ header: "ID Breeder", attribute: 'IdBreeder' },
	{ header: "ID Owner", attribute: 'IdOwner' },
	{ header: "fullname (sire)", attribute: 'FullnameSire' },
	{ header: "studbook number (sire)", attribute: 'StudbookNumberSire' },
	{ header: "fullname (dam)", attribute: 'FullnameDam' },
	{ header: "studbook number (dam)", attribute: 'StudbookNumberDam' },
	{ header: "studbook", attribute: 'Studbook' },
	{ header: "studbook number", attribute: 'StudbookNumber' },
	{ header: "chip number", attribute: 'ChipNumber' },
	{ header: "sex", attribute: 'Sex' },
	{ header: "date of birth", attribute: 'DateOfBirth' },
	{ header: "date of death", attribute: 'DateOfDeath' },
	{ header: "fertile", attribute: 'Fertile' },
	{ header: "color", attribute: 'Color' },
	{ header: "HD(G)", attribute: 'HdG' },
	{ header: "HD(G) / date", attribute: 'HdGDate' },
	{ header: "HD(G) / age", attribute: 'HdGAge' },
	{ header: "HD", attribute: 'Hd' },
	{ header: "HD / date", attribute: 'HdDate' },
	{ header: "HD / age", attribute: 'HdAge' },
	{ header: "Zähne", attribute: 'Zaehne' },
	{ header: "Zähne / date", attribute: 'ZaehneDate' },
	{ header: "Zähne / age", attribute: 'ZaehneAge' },
	{ header: "Gebiss", attribute: 'Gebiss' },
	{ header: "Gebiss / date", attribute: 'GebissDate' },
	{ header: "Gebiss / age", attribute: 'GebissAge' },
	{ header: "Nabel", attribute: 'Nabel' },
	{ header: "Nabel / date", attribute: 'NabelDate' },
	{ header: "Nabel / age", attribute: 'NabelAge' },
	{ header: "Gentest SOD1", attribute: 'GentestSod1' },
	{ header: "Gentest SOD1 / date", attribute: 'GentestSod1Date' },
	{ header: "Gentest SOD1 / age", attribute: 'GentestSod1Age' },
	{ header: "Schilddrüsentest", attribute: 'Schilddruesentest' },
	{ header: "Schilddrüsentest / date", attribute: 'SchilddruesentestDate' },
	{ header: "Schilddrüsentest / age", attribute: 'SchilddruesentestAge' },
	{ header: "Herzuntersuchung", attribute: 'Herzuntersuchung' },
	{ header: "Herzuntersuchung / date", attribute: 'HerzuntersuchungDate' },
	{ header: "Herzuntersuchung / age", attribute: 'HerzuntersuchungAge' },
	{ header: "Herzuntersuchung (kein zertifizierter Arzt des CC)", attribute: 'HerzuntersuchungKeinZertifizierterArztDesCc' },
	{ header: "Herzuntersuchung (kein zertifizierter Arzt des CC) / date", attribute: 'HerzuntersuchungKeinZertifizierterArztDesCcDate' },
	{ header: "Herzuntersuchung (kein zertifizierter Arzt des CC) / age", attribute: 'HerzuntersuchungKeinZertifizierterArztDesCcAge' },
	{ header: "Augenuntersuchung", attribute: 'Augenuntersuchung' },
	{ header: "Augenuntersuchung / date", attribute: 'AugenuntersuchungDate' },
	{ header: "Augenuntersuchung / age", attribute: 'AugenuntersuchungAge' },
	{ header: "Anaplasmose", attribute: 'Anaplasmose' },
	{ header: "Anaplasmose / date", attribute: 'AnaplasmoseDate' },
	{ header: "Anaplasmose / age", attribute: 'AnaplasmoseAge' },
	{ header: "Aortenstenose", attribute: 'Aortenstenose' },
	{ header: "Aortenstenose / date", attribute: 'AortenstenoseDate' },
	{ header: "Aortenstenose / age", attribute: 'AortenstenoseAge' },
	{ header: "Arthrose", attribute: 'Arthrose' },
	{ header: "Arthrose / date", attribute: 'ArthroseDate' },
	{ header: "Arthrose / age", attribute: 'ArthroseAge' },
	{ header: "Autoimmunerkrankung", attribute: 'Autoimmunerkrankung' },
	{ header: "Autoimmunerkrankung / date", attribute: 'AutoimmunerkrankungDate' },
	{ header: "Autoimmunerkrankung / age", attribute: 'AutoimmunerkrankungAge' },
	{ header: "Babesiose", attribute: 'Babesiose' },
	{ header: "Babesiose / date", attribute: 'BabesioseDate' },
	{ header: "Babesiose / age", attribute: 'BabesioseAge' },
	{ header: "Bandscheibenvorfall", attribute: 'Bandscheibenvorfall' },
	{ header: "Bandscheibenvorfall / date", attribute: 'BandscheibenvorfallDate' },
	{ header: "Bandscheibenvorfall / age", attribute: 'BandscheibenvorfallAge' },
	{ header: "Borreliose", attribute: 'Borreliose' },
	{ header: "Borreliose / date", attribute: 'BorrelioseDate' },
	{ header: "Borreliose / age", attribute: 'BorrelioseAge' },
	{ header: "Cauda equina", attribute: 'CaudaEquina' },
	{ header: "Cauda equina / date", attribute: 'CaudaEquinaDate' },
	{ header: "Cauda equina / age", attribute: 'CaudaEquinaAge' },
	{ header: "Dermoid", attribute: 'Dermoid' },
	{ header: "Dermoid / date", attribute: 'DermoidDate' },
	{ header: "Dermoid / age", attribute: 'DermoidAge' },
	{ header: "Dilative Kardiomyopathie (DCM)", attribute: 'DilativeKardiomyopathieDcm' },
	{ header: "Dilative Kardiomyopathie (DCM) / date", attribute: 'DilativeKardiomyopathieDcmDate' },
	{ header: "Dilative Kardiomyopathie (DCM) / age", attribute: 'DilativeKardiomyopathieDcmAge' },
	{ header: "Diabetes", attribute: 'Diabetes' },
	{ header: "Diabetes / date", attribute: 'DiabetesDate' },
	{ header: "Diabetes / age", attribute: 'DiabetesAge' },
	{ header: "DM (gesichert)", attribute: 'DmGesichert' },
	{ header: "DM (gesichert) / date", attribute: 'DmGesichertDate' },
	{ header: "DM (gesichert) / age", attribute: 'DmGesichertAge' },
	{ header: "DM (Verdacht)", attribute: 'DmVerdacht' },
	{ header: "DM (Verdacht) / date", attribute: 'DmVerdachtDate' },
	{ header: "DM (Verdacht) / age", attribute: 'DmVerdachtAge' },
	{ header: "Diversität DLA", attribute: 'DiversitaetDla' },
	{ header: "Diversität DLA / date", attribute: 'DiversitaetDlaDate' },
	{ header: "Diversität DLA / age", attribute: 'DiversitaetDlaAge' },
	{ header: "DNA-Profil", attribute: 'DnaProfil' },
	{ header: "DNA-Profil / date", attribute: 'DnaProfilDate' },
	{ header: "DNA-Profil / age", attribute: 'DnaProfilAge' },
	{ header: "Ellbogendysplasie (ED)", attribute: 'EllbogendysplasieEd' },
	{ header: "Ellbogendysplasie (ED) / date", attribute: 'EllbogendysplasieEdDate' },
	{ header: "Ellbogendysplasie (ED) / age", attribute: 'EllbogendysplasieEdAge' },
	{ header: "Ellenbogendysplasie (ED)", attribute: 'EllenbogendysplasieEd' },
	{ header: "Ellenbogendysplasie (ED) / date", attribute: 'EllenbogendysplasieEdDate' },
	{ header: "Ellenbogendysplasie (ED) / age", attribute: 'EllenbogendysplasieEdAge' },
	{ header: "Epilepsie", attribute: 'Epilepsie' },
	{ header: "Epilepsie / date", attribute: 'EpilepsieDate' },
	{ header: "Epilepsie / age", attribute: 'EpilepsieAge' },
	{ header: "D-Lokus", attribute: 'DLokus' },
	{ header: "D-Lokus / date", attribute: 'DLokusDate' },
	{ header: "D-Lokus / age", attribute: 'DLokusAge' },
	{ header: "Fellabweichung", attribute: 'Fellabweichung' },
	{ header: "Fellabweichung / date", attribute: 'FellabweichungDate' },
	{ header: "Fellabweichung / age", attribute: 'FellabweichungAge' },
	{ header: "Gallensäuretest", attribute: 'Gallensaeuretest' },
	{ header: "Gallensäuretest / date", attribute: 'GallensaeuretestDate' },
	{ header: "Gallensäuretest / age", attribute: 'GallensaeuretestAge' },
	{ header: "Gaumenspalte", attribute: 'Gaumenspalte' },
	{ header: "Gaumenspalte / date", attribute: 'GaumenspalteDate' },
	{ header: "Gaumenspalte / age", attribute: 'GaumenspalteAge' },
	{ header: "Hereditäre Katarakt (HC)", attribute: 'HereditaereKataraktHc' },
	{ header: "Hereditäre Katarakt (HC) / date", attribute: 'HereditaereKataraktHcDate' },
	{ header: "Hereditäre Katarakt (HC) / age", attribute: 'HereditaereKataraktHcAge' },
	{ header: "Hinterhandschwäche (unspez.)", attribute: 'HinterhandschwaecheUnspez' },
	{ header: "Hinterhandschwäche (unspez.) / date", attribute: 'HinterhandschwaecheUnspezDate' },
	{ header: "Hinterhandschwäche (unspez.) / age", attribute: 'HinterhandschwaecheUnspezAge' },
	{ header: "Hydrocephalus", attribute: 'Hydrocephalus' },
	{ header: "Hydrocephalus / date", attribute: 'HydrocephalusDate' },
	{ header: "Hydrocephalus / age", attribute: 'HydrocephalusAge' },
	{ header: "Hypothyreose (gesichert)", attribute: 'HypothyreoseGesichert' },
	{ header: "Hypothyreose (gesichert) / date", attribute: 'HypothyreoseGesichertDate' },
	{ header: "Hypothyreose (gesichert) / age", attribute: 'HypothyreoseGesichertAge' },
	{ header: "Hypothyreose (Verdacht)", attribute: 'HypothyreoseVerdacht' },
	{ header: "Hypothyreose (Verdacht) / date", attribute: 'HypothyreoseVerdachtDate' },
	{ header: "Hypothyreose (Verdacht) / age", attribute: 'HypothyreoseVerdachtAge' },
	{ header: "Infarkt", attribute: 'Infarkt' },
	{ header: "Infarkt / date", attribute: 'InfarktDate' },
	{ header: "Infarkt / age", attribute: 'InfarktAge' },
	{ header: "Infektion", attribute: 'Infektion' },
	{ header: "Infektion / date", attribute: 'InfektionDate' },
	{ header: "Infektion / age", attribute: 'InfektionAge' },
	{ header: "Kaiserschnitt", attribute: 'Kaiserschnitt' },
	{ header: "Kaiserschnitt / date", attribute: 'KaiserschnittDate' },
	{ header: "Kaiserschnitt / age", attribute: 'KaiserschnittAge' },
	{ header: "Kardiologische Erkrankungen", attribute: 'KardiologischeErkrankungen' },
	{ header: "Kardiologische Erkrankungen / date", attribute: 'KardiologischeErkrankungenDate' },
	{ header: "Kardiologische Erkrankungen / age", attribute: 'KardiologischeErkrankungenAge' },
	{ header: "Kehlkopflähmung", attribute: 'Kehlkopflaehmung' },
	{ header: "Kehlkopflähmung / date", attribute: 'KehlkopflaehmungDate' },
	{ header: "Kehlkopflähmung / age", attribute: 'KehlkopflaehmungAge' },
	{ header: "Lebershunt", attribute: 'Lebershunt' },
	{ header: "Lebershunt / date", attribute: 'LebershuntDate' },
	{ header: "Lebershunt / age", attribute: 'LebershuntAge' },
	{ header: "Leptospirose", attribute: 'Leptospirose' },
	{ header: "Leptospirose / date", attribute: 'LeptospiroseDate' },
	{ header: "Leptospirose / age", attribute: 'LeptospiroseAge' },
	{ header: "Lungenerkrankung", attribute: 'Lungenerkrankung' },
	{ header: "Lungenerkrankung / date", attribute: 'LungenerkrankungDate' },
	{ header: "Lungenerkrankung / age", attribute: 'LungenerkrankungAge' },
	{ header: "Magendrehung", attribute: 'Magendrehung' },
	{ header: "Magendrehung / date", attribute: 'MagendrehungDate' },
	{ header: "Magendrehung / age", attribute: 'MagendrehungAge' },
	{ header: "Milzdrehung", attribute: 'Milzdrehung' },
	{ header: "Milzdrehung / date", attribute: 'MilzdrehungDate' },
	{ header: "Milzdrehung / age", attribute: 'MilzdrehungAge' },
	{ header: "Morbus Cushing", attribute: 'MorbusCushing' },
	{ header: "Morbus Cushing / date", attribute: 'MorbusCushingDate' },
	{ header: "Morbus Cushing / age", attribute: 'MorbusCushingAge' },
	{ header: "Neurologische Erkrankungen", attribute: 'NeurologischeErkrankungen' },
	{ header: "Neurologische Erkrankungen / date", attribute: 'NeurologischeErkrankungenDate' },
	{ header: "Neurologische Erkrankungen / age", attribute: 'NeurologischeErkrankungenAge' },
	{ header: "Neurologische Erkrankung", attribute: 'NeurologischeErkrankung' },
	{ header: "Neurologische Erkrankung / date", attribute: 'NeurologischeErkrankungDate' },
	{ header: "Neurologische Erkrankung / age", attribute: 'NeurologischeErkrankungAge' },
	{ header: "Nierenerkrankung", attribute: 'Nierenerkrankung' },
	{ header: "Nierenerkrankung / date", attribute: 'NierenerkrankungDate' },
	{ header: "Nierenerkrankung / age", attribute: 'NierenerkrankungAge' },
	{ header: "Osteomyelitis", attribute: 'Osteomyelitis' },
	{ header: "Osteomyelitis / date", attribute: 'OsteomyelitisDate' },
	{ header: "Osteomyelitis / age", attribute: 'OsteomyelitisAge' },
	{ header: "Osteochondrosis dissecans (OCD)", attribute: 'OsteochondrosisDissecansOcd' },
	{ header: "Osteochondrosis dissecans (OCD) / date", attribute: 'OsteochondrosisDissecansOcdDate' },
	{ header: "Osteochondrosis dissecans (OCD) / age", attribute: 'OsteochondrosisDissecansOcdAge' },
	{ header: "Persist. Pupillarmembran (MPP)", attribute: 'PersistPupillarmembranMpp' },
	{ header: "Persist. Pupillarmembran (MPP) / date", attribute: 'PersistPupillarmembranMppDate' },
	{ header: "Persist. Pupillarmembran (MPP) / age", attribute: 'PersistPupillarmembranMppAge' },
	{ header: "Pneumothorax", attribute: 'Pneumothorax' },
	{ header: "Pneumothorax / date", attribute: 'PneumothoraxDate' },
	{ header: "Pneumothorax / age", attribute: 'PneumothoraxAge' },
	{ header: "Pyometra", attribute: 'Pyometra' },
	{ header: "Pyometra / date", attribute: 'PyometraDate' },
	{ header: "Pyometra / age", attribute: 'PyometraAge' },
	{ header: "Rüde hat in der HZD gedeckt", attribute: 'RuedeHatInDerHzdGedeckt' },
	{ header: "Rüde hat in der HZD gedeckt / date", attribute: 'RuedeHatInDerHzdGedecktDate' },
	{ header: "Rüde hat in der HZD gedeckt / age", attribute: 'RuedeHatInDerHzdGedecktAge' },
	{ header: "Rute", attribute: 'Rute' },
	{ header: "Rute / date", attribute: 'RuteDate' },
	{ header: "Rute / age", attribute: 'RuteAge' },
	{ header: "Rutenanomalie", attribute: 'Rutenanomalie' },
	{ header: "Rutenanomalie / date", attribute: 'RutenanomalieDate' },
	{ header: "Rutenanomalie / age", attribute: 'RutenanomalieAge' },
	{ header: "Verdacht auf Rutenanomalie", attribute: 'VerdachtAufRutenanomalie' },
	{ header: "Verdacht auf Rutenanomalie / date", attribute: 'VerdachtAufRutenanomalieDate' },
	{ header: "Verdacht auf Rutenanomalie / age", attribute: 'VerdachtAufRutenanomalieAge' },
	{ header: "Sebadenitis", attribute: 'Sebadenitis' },
	{ header: "Sebadenitis / date", attribute: 'SebadenitisDate' },
	{ header: "Sebadenitis / age", attribute: 'SebadenitisAge' },
	{ header: "Sepsis", attribute: 'Sepsis' },
	{ header: "Sepsis / date", attribute: 'SepsisDate' },
	{ header: "Sepsis / age", attribute: 'SepsisAge' },
	{ header: "Spondylose", attribute: 'Spondylose' },
	{ header: "Spondylose / date", attribute: 'SpondyloseDate' },
	{ header: "Spondylose / age", attribute: 'SpondyloseAge' },
	{ header: "Tumor Darm", attribute: 'TumorDarm' },
	{ header: "Tumor Darm / date", attribute: 'TumorDarmDate' },
	{ header: "Tumor Darm / age", attribute: 'TumorDarmAge' },
	{ header: "Tumor Hirn", attribute: 'TumorHirn' },
	{ header: "Tumor Hirn / date", attribute: 'TumorHirnDate' },
	{ header: "Tumor Hirn / age", attribute: 'TumorHirnAge' },
	{ header: "Tumor Knochen", attribute: 'TumorKnochen' },
	{ header: "Tumor Knochen / date", attribute: 'TumorKnochenDate' },
	{ header: "Tumor Knochen / age", attribute: 'TumorKnochenAge' },
	{ header: "Tumor Leber", attribute: 'TumorLeber' },
	{ header: "Tumor Leber / date", attribute: 'TumorLeberDate' },
	{ header: "Tumor Leber / age", attribute: 'TumorLeberAge' },
	{ header: "Tumor Lunge", attribute: 'TumorLunge' },
	{ header: "Tumor Lunge / date", attribute: 'TumorLungeDate' },
	{ header: "Tumor Lunge / age", attribute: 'TumorLungeAge' },
	{ header: "Tumor Magen", attribute: 'TumorMagen' },
	{ header: "Tumor Magen / date", attribute: 'TumorMagenDate' },
	{ header: "Tumor Magen / age", attribute: 'TumorMagenAge' },
	{ header: "Tumor Mamma", attribute: 'TumorMamma' },
	{ header: "Tumor Mamma / date", attribute: 'TumorMammaDate' },
	{ header: "Tumor Mamma / age", attribute: 'TumorMammaAge' },
	{ header: "Tumor Milz", attribute: 'TumorMilz' },
	{ header: "Tumor Milz / date", attribute: 'TumorMilzDate' },
	{ header: "Tumor Milz / age", attribute: 'TumorMilzAge' },
	{ header: "Tumor Pankreas", attribute: 'TumorPankreas' },
	{ header: "Tumor Pankreas / date", attribute: 'TumorPankreasDate' },
	{ header: "Tumor Pankreas / age", attribute: 'TumorPankreasAge' },
	{ header: "Tumor unspez./andere karzinogene Erkr.", attribute: 'TumorUnspezAndereKarzinogeneErkr' },
	{ header: "Tumor unspez./andere karzinogene Erkr. / date", attribute: 'TumorUnspezAndereKarzinogeneErkrDate' },
	{ header: "Tumor unspez./andere karzinogene Erkr. / age", attribute: 'TumorUnspezAndereKarzinogeneErkrAge' },
	{ header: "Wurfprotokolle", attribute: 'Wurfprotokolle' },
	{ header: "Wurfprotokolle / date", attribute: 'WurfprotokolleDate' },
	{ header: "Wurfprotokolle / age", attribute: 'WurfprotokolleAge' },
	{ header: "Verhalten II", attribute: 'VerhaltenIi' },
	{ header: "Verhalten II / date", attribute: 'VerhaltenIiDate' },
	{ header: "Verhalten II / age", attribute: 'VerhaltenIiAge' },
	{ header: "Verhalten III", attribute: 'VerhaltenIii' },
	{ header: "Verhalten III / date", attribute: 'VerhaltenIiiDate' },
	{ header: "Verhalten III / age", attribute: 'VerhaltenIiiAge' },
	{ header: "Verhalten III (E)", attribute: 'VerhaltenIiiE' },
	{ header: "Verhalten III (E) / date", attribute: 'VerhaltenIiiEDate' },
	{ header: "Verhalten III (E) / age", attribute: 'VerhaltenIiiEAge' },
	{ header: "Verhalten III (F)", attribute: 'VerhaltenIiiF' },
	{ header: "Verhalten III (F) / date", attribute: 'VerhaltenIiiFDate' },
	{ header: "Verhalten III (F) / age", attribute: 'VerhaltenIiiFAge' },
	{ header: "Verhalten III zurückgestellt", attribute: 'VerhaltenIiiZurueckgestellt' },
	{ header: "Verhalten III zurückgestellt / date", attribute: 'VerhaltenIiiZurueckgestelltDate' },
	{ header: "Verhalten III zurückgestellt / age", attribute: 'VerhaltenIiiZurueckgestelltAge' },
	{ header: "Verhalten III nicht bestanden", attribute: 'VerhaltenIiiNichtBestanden' },
	{ header: "Verhalten III nicht bestanden / date", attribute: 'VerhaltenIiiNichtBestandenDate' },
	{ header: "Verhalten III nicht bestanden / age", attribute: 'VerhaltenIiiNichtBestandenAge' },
	{ header: "Verhalten III Abbruch", attribute: 'VerhaltenIiiAbbruch' },
	{ header: "Verhalten III Abbruch / date", attribute: 'VerhaltenIiiAbbruchDate' },
	{ header: "Verhalten III Abbruch / age", attribute: 'VerhaltenIiiAbbruchAge' },
	{ header: "Verhalten IV", attribute: 'VerhaltenIv' },
	{ header: "Verhalten IV / date", attribute: 'VerhaltenIvDate' },
	{ header: "Verhalten IV / age", attribute: 'VerhaltenIvAge' },
	{ header: "Verhalten Veteranen", attribute: 'VerhaltenVeteranen' },
	{ header: "Verhalten Veteranen / date", attribute: 'VerhaltenVeteranenDate' },
	{ header: "Verhalten Veteranen / age", attribute: 'VerhaltenVeteranenAge' },
	{ header: "Körung (HZD)", attribute: 'KoerungHzd' },
	{ header: "Körung (HZD) / date", attribute: 'KoerungHzdDate' },
	{ header: "Körung (HZD) / age", attribute: 'KoerungHzdAge' },
	{ header: "Körung (HZD) (E)", attribute: 'KoerungHzdE' },
	{ header: "Körung (HZD) (E) / date", attribute: 'KoerungHzdEDate' },
	{ header: "Körung (HZD) (E) / age", attribute: 'KoerungHzdEAge' },
	{ header: "Körung (HZD) nicht bestanden", attribute: 'KoerungHzdNichtBestanden' },
	{ header: "Körung (HZD) nicht bestanden / date", attribute: 'KoerungHzdNichtBestandenDate' },
	{ header: "Körung (HZD) nicht bestanden / age", attribute: 'KoerungHzdNichtBestandenAge' },
	{ header: "Jugendkörung (HZD)", attribute: 'JugendkoerungHzd' },
	{ header: "Jugendkörung (HZD) / date", attribute: 'JugendkoerungHzdDate' },
	{ header: "Jugendkörung (HZD) / age", attribute: 'JugendkoerungHzdAge' },
	{ header: "Richterbericht", attribute: 'Richterbericht' },
	{ header: "Richterbericht / date", attribute: 'RichterberichtDate' },
	{ header: "Richterbericht / age", attribute: 'RichterberichtAge' },
	{ header: "Übernahme ins HZD Zuchtbuch", attribute: 'UebernahmeInsHzdZuchtbuch' },
	{ header: "Übernahme ins HZD Zuchtbuch / date", attribute: 'UebernahmeInsHzdZuchtbuchDate' },
	{ header: "Übernahme ins HZD Zuchtbuch / age", attribute: 'UebernahmeInsHzdZuchtbuchAge' },
	{ header: "Zuchtzulassung", attribute: 'Zuchtzulassung' },
	{ header: "Zuchtzulassung / date", attribute: 'ZuchtzulassungDate' },
	{ header: "Zuchtzulassung / age", attribute: 'ZuchtzulassungAge' },
	{ header: "Zuchthündin im Zwinger", attribute: 'ZuchthuendinImZwinger' },
	{ header: "Zuchthündin im Zwinger / date", attribute: 'ZuchthuendinImZwingerDate' },
	{ header: "Zuchthündin im Zwinger / age", attribute: 'ZuchthuendinImZwingerAge' },
	{ header: "Zuchtzulassung mit Auflagen", attribute: 'ZuchtzulassungMitAuflagen' },
	{ header: "Zuchtzulassung mit Auflagen / date", attribute: 'ZuchtzulassungMitAuflagenDate' },
	{ header: "Zuchtzulassung mit Auflagen / age", attribute: 'ZuchtzulassungMitAuflagenAge' },
	{ header: "Anmerkungen/sonst. Befunde (nicht auswertbar!)", attribute: 'AnmerkungenSonstBefundeNichtAuswertbar' },
	{ header: "Anmerkungen/sonst. Befunde (nicht auswertbar!) / date", attribute: 'AnmerkungenSonstBefundeNichtAuswertbarDate' },
	{ header: "Anmerkungen/sonst. Befunde (nicht auswertbar!) / age", attribute: 'AnmerkungenSonstBefundeNichtAuswertbarAge' },
	{ header: "Kryptorchide", attribute: 'Kryptorchide' },
	{ header: "Kryptorchide / date", attribute: 'KryptorchideDate' },
	{ header: "Kryptorchide / age", attribute: 'KryptorchideAge' },
	{ header: "Monorchide", attribute: 'Monorchide' },
	{ header: "Monorchide / date", attribute: 'MonorchideDate' },
	{ header: "Monorchide / age", attribute: 'MonorchideAge' },
	{ header: "Tumor Hoden", attribute: 'TumorHoden' },
	{ header: "Tumor Hoden / date", attribute: 'TumorHodenDate' },
	{ header: "Tumor Hoden / age", attribute: 'TumorHodenAge' },
]
