export interface CsCsvColumn {
	header: string
	attribute: string
}

export const CS_DOG_COLUMNS: CsCsvColumn[] = [
	{ header: "ID Animal", attribute: 'IdAnimal' },
	{ header: "Given Name", attribute: 'GivenName' },
	{ header: "Name of Breeding Station", attribute: 'NameOfBreedingStation' },
	{ header: "Full Name", attribute: 'FullName' },
	{ header: "ID Breeder", attribute: 'IdBreeder' },
	{ header: "ID Owner", attribute: 'IdOwner' },
	{ header: "fullname (sire)", attribute: 'FullnameSire' },
	{ header: "studbook number (sire)", attribute: 'StudbookNumberSire' },
	{ header: "fullname (dam)", attribute: 'FullnameDam' },
	{ header: "studbook number (dam)", attribute: 'StudbookNumberDam' },
	{ header: "studbook", attribute: 'Studbook' },
	{ header: "studbook number", attribute: 'StudbookNumber' },
	{ header: "chip number", attribute: 'ChipNumber' },
	{ header: "sex", attribute: 'Sex' },
	{ header: "date of birth", attribute: 'DateOfBirth' },
	{ header: "date of death", attribute: 'DateOfDeath' },
	{ header: "fertile", attribute: 'Fertile' },
	{ header: "color", attribute: 'Color' },
	{ header: "HD(G)", attribute: 'HdG' },
	{ header: "HD(G) / date", attribute: 'HdGDate' },
	{ header: "HD(G) / age", attribute: 'HdGAge' },
	{ header: "HD", attribute: 'Hd' },
	{ header: "HD / date", attribute: 'HdDate' },
	{ header: "HD / age", attribute: 'HdAge' },
	{ header: "Zähne", attribute: 'Zaehne' },
	{ header: "Zähne / date", attribute: 'ZaehneDate' },
	{ header: "Zähne / age", attribute: 'ZaehneAge' },
	{ header: "Gebiss", attribute: 'Gebiss' },
	{ header: "Gebiss / date", attribute: 'GebissDate' },
	{ header: "Gebiss / age", attribute: 'GebissAge' },
	{ header: "Nabel", attribute: 'Nabel' },
	{ header: "Nabel / date", attribute: 'NabelDate' },
	{ header: "Nabel / age", attribute: 'NabelAge' },
	{ header: "Gentest SOD1", attribute: 'GentestSod1' },
	{ header: "Gentest SOD1 / date", attribute: 'GentestSod1Date' },
	{ header: "Gentest SOD1 / age", attribute: 'GentestSod1Age' },
	{ header: "Schilddrüsentest", attribute: 'Schilddruesentest' },
	{ header: "Schilddrüsentest / date", attribute: 'SchilddruesentestDate' },
	{ header: "Schilddrüsentest / age", attribute: 'SchilddruesentestAge' },
	{ header: "Herzuntersuchung", attribute: 'Herzuntersuchung' },
	{ header: "Herzuntersuchung / date", attribute: 'HerzuntersuchungDate' },
	{ header: "Herzuntersuchung / age", attribute: 'HerzuntersuchungAge' },
	{ header: "Herzuntersuchung (kein zertifizierter Arzt des CC)", attribute: 'HerzuntersuchungKeinZertifizierterArztDesCc' },
	{ header: "Herzuntersuchung (kein zertifizierter Arzt des CC) / date", attribute: 'HerzuntersuchungKeinZertifizierterArztDesCcDate' },
	{ header: "Herzuntersuchung (kein zertifizierter Arzt des CC) / age", attribute: 'HerzuntersuchungKeinZertifizierterArztDesCcAge' },
	{ header: "Augenuntersuchung", attribute: 'Augenuntersuchung' },
	{ header: "Augenuntersuchung / date", attribute: 'AugenuntersuchungDate' },
	{ header: "Augenuntersuchung / age", attribute: 'AugenuntersuchungAge' },
	{ header: "Wurfprotokolle", attribute: 'Wurfprotokolle' },
	{ header: "Wurfprotokolle / date", attribute: 'WurfprotokolleDate' },
	{ header: "Wurfprotokolle / age", attribute: 'WurfprotokolleAge' },
	{ header: "Verhalten II", attribute: 'VerhaltenIi' },
	{ header: "Verhalten II / date", attribute: 'VerhaltenIiDate' },
	{ header: "Verhalten II / age", attribute: 'VerhaltenIiAge' },
	{ header: "Verhalten III", attribute: 'VerhaltenIii' },
	{ header: "Verhalten III / date", attribute: 'VerhaltenIiiDate' },
	{ header: "Verhalten III / age", attribute: 'VerhaltenIiiAge' },
	{ header: "Verhalten III (E)", attribute: 'VerhaltenIiiE' },
	{ header: "Verhalten III (E) / date", attribute: 'VerhaltenIiiEDate' },
	{ header: "Verhalten III (E) / age", attribute: 'VerhaltenIiiEAge' },
	{ header: "Verhalten III (F)", attribute: 'VerhaltenIiiF' },
	{ header: "Verhalten III (F) / date", attribute: 'VerhaltenIiiFDate' },
	{ header: "Verhalten III (F) / age", attribute: 'VerhaltenIiiFAge' },
	{ header: "Verhalten III zurückgestellt", attribute: 'VerhaltenIiiZurueckgestellt' },
	{ header: "Verhalten III zurückgestellt / date", attribute: 'VerhaltenIiiZurueckgestelltDate' },
	{ header: "Verhalten III zurückgestellt / age", attribute: 'VerhaltenIiiZurueckgestelltAge' },
	{ header: "Verhalten III nicht bestanden", attribute: 'VerhaltenIiiNichtBestanden' },
	{ header: "Verhalten III nicht bestanden / date", attribute: 'VerhaltenIiiNichtBestandenDate' },
	{ header: "Verhalten III nicht bestanden / age", attribute: 'VerhaltenIiiNichtBestandenAge' },
	{ header: "Verhalten III Abbruch", attribute: 'VerhaltenIiiAbbruch' },
	{ header: "Verhalten III Abbruch / date", attribute: 'VerhaltenIiiAbbruchDate' },
	{ header: "Verhalten III Abbruch / age", attribute: 'VerhaltenIiiAbbruchAge' },
	{ header: "Verhalten IV", attribute: 'VerhaltenIv' },
	{ header: "Verhalten IV / date", attribute: 'VerhaltenIvDate' },
	{ header: "Verhalten IV / age", attribute: 'VerhaltenIvAge' },
	{ header: "Verhalten Veteranen", attribute: 'VerhaltenVeteranen' },
	{ header: "Verhalten Veteranen / date", attribute: 'VerhaltenVeteranenDate' },
	{ header: "Verhalten Veteranen / age", attribute: 'VerhaltenVeteranenAge' },
	{ header: "Körung (HZD)", attribute: 'KoerungHzd' },
	{ header: "Körung (HZD) / date", attribute: 'KoerungHzdDate' },
	{ header: "Körung (HZD) / age", attribute: 'KoerungHzdAge' },
	{ header: "Körung (HZD) (E)", attribute: 'KoerungHzdE' },
	{ header: "Körung (HZD) (E) / date", attribute: 'KoerungHzdEDate' },
	{ header: "Körung (HZD) (E) / age", attribute: 'KoerungHzdEAge' },
	{ header: "Körung (HZD) nicht bestanden", attribute: 'KoerungHzdNichtBestanden' },
	{ header: "Körung (HZD) nicht bestanden / date", attribute: 'KoerungHzdNichtBestandenDate' },
	{ header: "Körung (HZD) nicht bestanden / age", attribute: 'KoerungHzdNichtBestandenAge' },
	{ header: "Jugendkörung (HZD)", attribute: 'JugendkoerungHzd' },
	{ header: "Jugendkörung (HZD) / date", attribute: 'JugendkoerungHzdDate' },
	{ header: "Jugendkörung (HZD) / age", attribute: 'JugendkoerungHzdAge' },
	{ header: "Richterbericht", attribute: 'Richterbericht' },
	{ header: "Richterbericht / date", attribute: 'RichterberichtDate' },
	{ header: "Richterbericht / age", attribute: 'RichterberichtAge' },
	{ header: "Übernahme ins HZD Zuchtbuch", attribute: 'UebernahmeInsHzdZuchtbuch' },
	{ header: "Übernahme ins HZD Zuchtbuch / date", attribute: 'UebernahmeInsHzdZuchtbuchDate' },
	{ header: "Übernahme ins HZD Zuchtbuch / age", attribute: 'UebernahmeInsHzdZuchtbuchAge' },
	{ header: "Zuchtzulassung", attribute: 'Zuchtzulassung' },
	{ header: "Zuchtzulassung / date", attribute: 'ZuchtzulassungDate' },
	{ header: "Zuchtzulassung / age", attribute: 'ZuchtzulassungAge' },
	{ header: "Zuchthündin im Zwinger", attribute: 'ZuchthuendinImZwinger' },
	{ header: "Zuchthündin im Zwinger / date", attribute: 'ZuchthuendinImZwingerDate' },
	{ header: "Zuchthündin im Zwinger / age", attribute: 'ZuchthuendinImZwingerAge' },
	{ header: "Zuchtzulassung mit Auflagen", attribute: 'ZuchtzulassungMitAuflagen' },
	{ header: "Zuchtzulassung mit Auflagen / date", attribute: 'ZuchtzulassungMitAuflagenDate' },
	{ header: "Zuchtzulassung mit Auflagen / age", attribute: 'ZuchtzulassungMitAuflagenAge' },
	{ header: "Anmerkungen/sonst. Befunde (nicht auswertbar!)", attribute: 'AnmerkungenSonstBefundeNichtAuswertbar' },
	{ header: "Anmerkungen/sonst. Befunde (nicht auswertbar!) / date", attribute: 'AnmerkungenSonstBefundeNichtAuswertbarDate' },
	{ header: "Anmerkungen/sonst. Befunde (nicht auswertbar!) / age", attribute: 'AnmerkungenSonstBefundeNichtAuswertbarAge' },
]
