plugins {
    id 'java'
    id 'application'
    id 'io.quarkus' version '3.37.4'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('io.quarkus:quarkus-bom:3.37.4')

    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-rest'
    implementation 'io.quarkus:quarkus-rest-jackson'
    implementation 'io.quarkus:quarkus-config-yaml'
    implementation 'io.quarkus:quarkus-rest-client-jackson'
    implementation 'io.quarkus:quarkus-scheduler'
    implementation 'io.quarkus:quarkus-vertx'
    implementation 'io.vertx:vertx-web-client'

    implementation 'org.apache.commons:commons-csv:1.10.0'

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured:5.4.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'de.hzd.importer.Application'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}
