CREATE TABLE csv_members (
	c_id INTEGER NOT NULL,
	c_flag_access BOOLEAN,
	title VARCHAR(255),
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	address1 VARCHAR(255),
	zip VARCHAR(20),
	city VARCHAR(255),
	region VARCHAR(32),
	country_code VARCHAR(8),
	phone VARCHAR(50),
	email VARCHAR(255),
	sex VARCHAR(8),
	c_flag_breeder BOOLEAN,
	membership_number INTEGER,
	breeding_station VARCHAR(255),
	date_of_birth DATE,
	date_of_death DATE,
	member_since DATE,
	cancellation_on DATE,
	is_active_breeder BOOLEAN,
	CONSTRAINT csv_members_pkey PRIMARY KEY (c_id)
);

CREATE TABLE csv_dogs (
	c_id INTEGER NOT NULL,
	given_name VARCHAR(255),
	full_kennel_name VARCHAR(500),
	breeder_id INTEGER,
	owner_id INTEGER,
	chip_number VARCHAR(50),
	sex VARCHAR(8),
	date_of_birth DATE,
	date_of_death DATE,
	c_fertile BOOLEAN,
	hd VARCHAR(16),
	sod1 VARCHAR(32),
	heart_check BOOLEAN,
	eyes_check BOOLEAN,
	genprofil BOOLEAN,
	color VARCHAR(32),
	studbook_number VARCHAR(255),
	studbook_number_father VARCHAR(255),
	studbook_number_mother VARCHAR(255),
	exhibitions TEXT,
	breed_survey TEXT,
	breeder_kennel_name VARCHAR(500),
	CONSTRAINT csv_dogs_pkey PRIMARY KEY (c_id)
);
